AWSTemplateFormatVersion: '2010-09-09'
Description: '340B Compute Module - ALB, ASG, Launch Template'

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, qa, prod]
    Description: Environment name
  Region:
    Type: String
    Default: us-west-1
    Description: AWS Region
  NamingPrefix:
    Type: String
    Default: 340b
    Description: Naming prefix for all resources
  InstanceType:
    Type: String
    Default: t3.micro
    Description: EC2 instance type
  MinSize:
    Type: Number
    Default: 2
    Description: Minimum number of instances in ASG
  MaxSize:
    Type: Number
    Default: 4
    Description: Maximum number of instances in ASG
  DesiredCapacity:
    Type: Number
    Default: 2
    Description: Desired number of instances in ASG
  KeyName:
    Type: String
    Description: EC2 Key Pair name for SSH access (optional)
    Default: ''
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID from network stack
  PublicSubnet1Id:
    Type: AWS::EC2::Subnet::Id
    Description: Public subnet 1 for ALB
  PublicSubnet2Id:
    Type: AWS::EC2::Subnet::Id
    Description: Public subnet 2 for ALB
  PrivateSubnet1Id:
    Type: AWS::EC2::Subnet::Id
    Description: Private subnet 1 for EC2
  PrivateSubnet2Id:
    Type: AWS::EC2::Subnet::Id
    Description: Private subnet 2 for EC2
  ALBSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: ALB security group
  EC2SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: EC2 security group
  CertificateArn:
    Type: String
    Default: ''
    Description: ACM certificate ARN for HTTPS (optional)

Conditions:
  UseCertificate: !Not [!Equals [!Ref CertificateArn, '']]
  UseKeyName: !Not [!Equals [!Ref KeyName, '']]

Resources:
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub '${NamingPrefix}-${Environment}-api-lt'
      LaunchTemplateData:
        ImageId: !Sub '{{resolve:ssm:/aws/service/canonical/ubuntu/server/24.04/stable/current/amd64/hvm/ebs-gp3/ami-id}}'
        InstanceType: !Ref InstanceType
        KeyName: !If [UseKeyName, !Ref KeyName, !Ref 'AWS::NoValue']
        IamInstanceProfile:
          Arn: !GetAtt EC2InstanceProfile.Arn
        SecurityGroupIds:
          - !Ref EC2SecurityGroupId
        BlockDeviceMappings:
          - DeviceName: /dev/sda1
            Ebs:
              VolumeSize: 20
              VolumeType: gp3
              Encrypted: true
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            apt-get update -y
            apt-get install -y nginx
            systemctl enable nginx
            systemctl start nginx
            echo "<h1>340B ${Environment} API</h1>" > /var/www/html/index.html
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: !Sub '${NamingPrefix}-${Environment}-api-${Region}'
              - Key: Environment
                Value: !Ref Environment

  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2InstanceRole

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub '${NamingPrefix}-${Environment}-alb'
      Type: application
      Scheme: internet-facing
      IpAddressType: ipv4
      Subnets:
        - !Ref PublicSubnet1Id
        - !Ref PublicSubnet2Id
      SecurityGroups:
        - !Ref ALBSecurityGroupId
      Tags:
        - Key: Name
          Value: !Sub '${NamingPrefix}-${Environment}-alb'
        - Key: Environment
          Value: !Ref Environment

  ALBListenerHTTP:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  ALBListenerHTTPS:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Condition: UseCertificate
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref CertificateArn
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub '${NamingPrefix}-${Environment}-tg'
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VpcId
      TargetType: instance
      HealthCheckEnabled: true
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 30
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Tags:
        - Key: Name
          Value: !Sub '${NamingPrefix}-${Environment}-tg'

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub '${NamingPrefix}-${Environment}-api-asg'
      VPCZoneIdentifier:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MinSize: !Ref MinSize
      MaxSize: !Ref MaxSize
      DesiredCapacity: !Ref DesiredCapacity
      TargetGroupARNs:
        - !Ref TargetGroup
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300
      Tags:
        - Key: Name
          Value: !Sub '${NamingPrefix}-${Environment}-api-asg'
          PropagateAtLaunch: true
        - Key: Environment
          Value: !Ref Environment
          PropagateAtLaunch: true

Outputs:
  LoadBalancerArn:
    Description: ALB ARN for WAF association
    Value: !Ref ApplicationLoadBalancer
    Export:
      Name: !Sub '${NamingPrefix}-${Environment}-LoadBalancerArn'
  LoadBalancerDNSName:
    Description: ALB DNS name
    Value: !GetAtt ApplicationLoadBalancer.DNSName
    Export:
      Name: !Sub '${NamingPrefix}-${Environment}-LoadBalancerDNSName'
  LoadBalancerHostedZoneId:
    Description: ALB hosted zone ID
    Value: !GetAtt ApplicationLoadBalancer.CanonicalHostedZoneID
    Export:
      Name: !Sub '${NamingPrefix}-${Environment}-LoadBalancerHostedZoneId'
  TargetGroupArn:
    Description: Target group ARN
    Value: !Ref TargetGroup
    Export:
      Name: !Sub '${NamingPrefix}-${Environment}-TargetGroupArn'
  AutoScalingGroupName:
    Description: Auto Scaling Group name
    Value: !Ref AutoScalingGroup
    Export:
      Name: !Sub '${NamingPrefix}-${Environment}-AutoScalingGroupName'
