AWSTemplateFormatVersion: '2010-09-09'
Description: '340B Security Module - AWS WAF Web ACL for ALB'

Parameters:
  LoadBalancerArn:
    Type: String
    Description: ARN of the ALB to attach WAF to
  Environment:
    Type: String
    AllowedValues: [dev, qa, prod]
    Description: Environment name
  Region:
    Type: String
    Default: us-west-1
    Description: AWS Region
  NamingPrefix:
    Type: String
    Default: 340b
    Description: Naming prefix for all resources
  AllowedIPRanges:
    Type: CommaDelimitedList
    Default: ''
    Description: Optional comma-separated IP ranges to allow (empty = allow all)

Resources:
  WAFWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub '${NamingPrefix}-${Environment}-waf-acl'
      Scope: REGIONAL
      DefaultAction:
        Allow: {}
      Description: WAF Web ACL for 340B ALB
      Rules:
        - Name: AWS-AWSManagedRulesCommonRuleSet
          Priority: 1
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesCommonRuleSetMetric
        - Name: AWS-AWSManagedRulesKnownBadInputsRuleSet
          Priority: 2
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesKnownBadInputsRuleSetMetric
        - Name: RateLimitRule
          Priority: 3
          Action:
            Block: {}
          Statement:
            RateBasedStatement:
              Limit: 2000
              AggregateKeyType: IP
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RateLimitRuleMetric
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub '${NamingPrefix}-${Environment}-waf-metric'
      Tags:
        - Key: Name
          Value: !Sub '${NamingPrefix}-${Environment}-waf-acl'
        - Key: Environment
          Value: !Ref Environment

  WAFAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    Properties:
      ResourceArn: !Ref LoadBalancerArn
      WebACLArn: !GetAtt WAFWebACL.Arn

Outputs:
  WAFWebACLArn:
    Description: WAF Web ACL ARN
    Value: !GetAtt WAFWebACL.Arn
    Export:
      Name: !Sub '${NamingPrefix}-${Environment}-WAFWebACLArn'
